### Recuperar todas las peliculas
GET http://api-node-mysql-production-de7d.up.railway.app/movies

### Recuperar una pelicula por id
GET http://localhost:1234/movies/c4060603-66ee-11ef-a9ca-54b20390c007

### Recuperar todas las peliculas por genero
GET http://localhost:1234/movies?genre=Action

### Crear una pelicula con POST
POST http://api-node-mysql-production-de7d.up.railway.app/movies/create
Content-Type: application/json

{
  "title": "Naruto, Proteger la aldea de cascadas",
  "year": 2000,
  "director": "Masashi Kishimoto",
  "duration": 125,
  "poster": "https://static.wikia.nocookie.net/doblaje/images/0/09/LatinAmerican_ResurrectionF_Poster.png/revision/latest?cb=20150319060957&path-prefix=es",
  "genre": ["Action", "Adventure"]
}


### Actualizar una pelicula

PATCH http://api-node-mysql-production-de7d.up.railway.app/movies/update/e24f345c-6945-11ef-87c7-a2aa990475b6
Content-Type: application/json

{
  "rate": 7.5
}

### Eliminar una pelicula por id
DELETE http://api-node-mysql-production-de7d.up.railway.app/movies/6c962927-66ee-11ef-a9ca-54b20390c007